---
title: 'Stat 415 Regression: Classwork/Lab 6 (Matricies)'
author: "Frankie Tyndall"
date: '2022-07-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(expm)
```

## The Matricies


```{r}
A <- matrix(c(10, 8,
              5, 12), ncol = 2, byrow = TRUE)

B <- matrix(c(5, 3,
              15, 6), ncol = 2, byrow = TRUE)

D <- matrix(c(-3, 7, 2,
              3, -2, -10), ncol = 3, byrow = TRUE)

E <- matrix(c(1, -4, 5, -10,
              6, 0, -3,  6,
              12, 5,-11, -4), ncol = 4, byrow = TRUE)

G <- matrix(c(-3, 7, 2, 7,
              3, -2, -10, -2,
              1,  0, 5, -10), ncol = 4, byrow = TRUE)


```

## Multiply E and G

```{r}
multiply_EG <- E*G
multiply_EG
```
## Find Transpose of matrix E

```{r}
transpose_E <- t(E)
transpose_E
```
## Find Inverse of B

```{r}
inverse_B <- solve(B)
inverse_B
```
## Find the sum of two transpose of D

```{r}
transpose_D <- t(D)

SUM_transpose_D <- transpose_D + transpose_D
SUM_transpose_D
```
## Find the Transpose of the inverse of A

```{r}
inverse_A <- solve(A)
Transpose_Inverse_A <- t(inverse_A)
Transpose_Inverse_A
```
## Find the inverse of the inverse of B multiplied by the transpose of B

```{r}
transpose_B <- t(B)
multiply_Inverse_Transpose_B <- inverse_B * transpose_B
inverse_Inverse_Transpose_B <- solve(multiply_Inverse_Transpose_B)
inverse_Inverse_Transpose_B
```
